apiVersion: apps/v1
kind: Deployment
metadata:
  name: koa
  labels:
    app: koa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koa
  template:
    metadata:
      labels:
        app: koa
    spec:
      containers:
      - name: koa
        image: ghcr.io/${IMAGE_NAME}:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
        ports:
        - containerPort: 3000
