apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  labels:
    app: ingress-upstream
spec:
  selector:
    app: koa
  ports:
    - name: 80-to-3000
      protocol: TCP
      port: 80
      targetPort: 3000
